name: cicd

on: [push, pull_request]

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
      - uses: jurassiscripts/setup-velociraptor@v1
      - name: ci
        run: VR_HOOKS=false vr ci
      - name: cd
        run: echo 'not implemented yet.'
